### ISSUE TITLE
Unicode symbols path or file name cause ERROR: Could not load image file

### ISSUE THREAD

**Issue by Bxaa** [pgrit/SimpleImageIO#6]
Hi,
Seems to be you should add and use CharSet.Unicode+ MarshalAs(UnmanagedType.LPWStr) for strings in all pinvoke's declare that send path to native dll and fix fuctions in native dll's
(Maybe I'm wrong and this is not the problem, but simply renaming the file solves the problem, I didn't look at all your code (you better do it)

Code to reproduce (.Net\Net6):
Just 
`New RgbImage("file name or path with unicode symbols")`

Example - name with unicode 'X' symbol (correct Radiance Rgbe\HDR for test):
https://drive.google.com/file/d/1_QqwroWibzEI6C_MVbHakumAMw3FZy1s/view?usp=sharing

This error will occur with all non latin paths or names and this is bad (chiness, cyrillic, etc)

Thx for your project

**Comment by pgrit** [comment]
Hi,
I am aware of this limitation, it has been on my backlog for a while. A proper cross-platform solution will need some tinkering, since there are multiple third-party dependencies that each may or may not have some form of Unicode support, and since Windows requires UTF-16 and Linux/OSX work with UTF-8.
Since I don't have much time at the moment, this will have to remain on the backlog for the time being.
